### ISSUE TITLE
Kleibergen-Paap test code broken; Effective F-statistic implementation

### ISSUE THREAD

**Issue by apoorvalal** [lrberge/fixest#161]
## K-P error 

Computing the Kleibergen-Paap F-statistic using  `fitstat(mod, "kpr")` produces the following error with the dev version of `fixest`. The equivalent computation in `lfe` works fine (and is identical to the documented `ivreg2` version in stata).

```
Error in str2lang(value_raw): <text>:2:0: unexpected end of input
1: (+Intercept
   ^
Traceback:

1. fitstat(m_feols, "kpr")
2. kp_stat(x)
3. proj_on_U(x, Z)
4. resid(feols.fit(Z, U))
5. feols.fit(Z, U)
6. feols(env = env)
7. .xpd(rhs = fml[[3]])
8. value2stringCall(rhs, call = TRUE, check = check)
9. str2lang(value_raw)
```

MWE:

```{r}
library(data.table); library(fixest); library(lfe)
set.seed(42)
N = 1e3
df = data.table(
  e = rnorm(N),
  z1 = rbinom(N, 1, 0.3),
  z2 = rnorm(N)
)
df[, x := 0.2 * z1 + 0.3 * z2 + e * 1.5][
    ,y := x + e]

# %%
m_felm = felm(y ~ 1 | 0 | (x ~ z1 + z2), df)
# KP F stat in LFE object / identical in stata's ivreg2
m_felm$stage1$rob.iv1fstat

# %%
m_feols = feols(y ~ 1 | x ~ z1 + z2, df)
fitstat(m_feols, "kpr")
# error
```

## Effective F statistic

Also I was wondering if there's any interest in including the effective F statistic (which is identical to K-P in just-identified single-instrument+single-treatment settings - see [2] for details ).
 
As part of a review paper I'm working on with coauthors, I'm implementing the Pflueger-Montiel Olea Effective F statistic [1], which is recommended by the review paper by Andrews, Stock, and Sun [2] manually for now using the simplified formula 
![image](https://user-images.githubusercontent.com/12086926/121828291-ffcf1980-cc73-11eb-8ef3-e2291be01571.png)

from the Andrews et al paper (the original paper is written in archaic notation with y and Y as the outcome and treatment respectively; ew). 
Pretty straightforward to implement / I can send a pull request with the implementation if you think there's enough interest.
 
happy to move to related F-stat thread if preferred https://github.com/lrberge/fixest/issues/117

[1] http://www.joseluismontielolea.com/Montiel-OleaJBES.pdf
[2] https://scholar.harvard.edu/files/wirev_092218-_corrected_0.pdf

**Comment by lrberge** [comment]
Hey, thanks for the report!

### KP problem

I've corrected the bug which was due to the fit method not handling variables with non-standard names.

Now the KP works:

```R
fitstat(m_feols, "kpr")
#> Kleibergen-Paap: stat = 0.673883, p = 0.713951, on 2 DoF.
```

I must say that the current KP implementation is the same as Stata **only** when n_inst = n_exo and it diverges when n_exo > n_inst. I don't know the cause and I think I may just put NA instead when n_inst < n_exo. But I would be very happy if you could (or if you know someone who could) fix the KP code (which is a nightmare btw! :-)).

### F stat

Isn't it similar to the Wald in `fitstat`? If you pick the right VCOV, you obtain the same tests as a KP with a single instrument:
```R
m_felm$stage1$rob.iv1fstat
#> $x
#>            p         chi2          df1          p.F            F          df2 
#> 1.452699e-09 4.069969e+01 2.000000e+00 2.176714e-09 2.034984e+01 9.970000e+02 
#> attr(,"formula")
#> ~z1 | z2
#> <environment: 0x00000254374e6460>

fitstat(m_feols, "ivwald", se = "heter")
#> Wald (1st stage), x: stat = 20.3, p = 2.177e-9, on 2 and 997 DoF, VCOV: Heteroskedasticity-robust.
```

**Comment by etiennebacher** [comment]
Hello,

I think this bug is back but with another error message. With the Github version:
```
library(data.table)
library(fixest)

set.seed(42)
N = 1e3
df = data.table(
  e = rnorm(N),
  z1 = rbinom(N, 1, 0.3),
  z2 = rnorm(N)
)
df[, x := 0.2 * z1 + 0.3 * z2 + e * 1.5][
  ,y := x + e]

m_feols = feols(y ~ 1 | x ~ z1 + z2, df)
fitstat(m_feols, "kpr")
```
```
Error in kronv %*% vhat : non-conformable arguments
```

**Comment by lrberge** [comment]
Indeed, thanks: that's fixed.

**Comment by adamaltmejd** [comment]
`fitstat(x, "kpr")` does not seem to work with an estimation run with `lean = TRUE` even if I manually set vcov to use the same clusters as was initially used by `feols()`. Is this on purpose? Does `fitstat(x, "kpr")` need to recalculate se's?

**Comment by lrberge** [comment]
You need the VCOV indeed.

**Comment by adamaltmejd** [comment]
Thanks!

**Comment by adamaltmejd** [comment]
Found another bug. When there are missing values in the instrumented variable the KPR calculation throws:
 `Error in svd(theta) : infinite or missing values in 'x'`

**Comment by adamaltmejd** [comment]
I also get different errors when I try to extract KPR stats where the instrument is interacted. Eg:

```
library(data.table)
library(fixest)
set.seed(42)
N = 1e3
df = data.table(
  e = rnorm(N),
  z1 = rbinom(N, 1, 0.3),
  z2 = rnorm(N),
  int = c(rep(1, 1e3), rep(0, 2e3))
)
df[, x := 0.2 * z1 + 0.3 * z2 + e * 1.5][
  ,y := x + e]

m_feols = feols(y ~ 1 | x * int ~ z1 * int, df)
fitstat(m_feols, "kpr")
```

```
Error in solve.default(t(Gmat)) : 
  system is computationally singular: reciprocal condition number = 1.26152e-16
```

In my actual data I also get the error:

```
Error in chol.default(crossprod(X_proj)) :                                                                                                                                               
  the leading minor of order 1 is not positive definite  
```

**Comment by lrberge** [comment]
Thanks for reporting:
 - I won't fix the bug since I don't understand the underlying method well.
 - I'm really considering removing this statistics altogether since it's buggy and I can't fix.

On my side I already spent a lot of time implementing it and can't spend more time on it especially that I don't use it. There is just too many implicit knowledge in the paper and I don't have the time to dig into it. 
Maybe one of you could take a stab at it?  @apoorvalal? you seem super algebra-aware? ;-)

**Comment by adamaltmejd** [comment]
Makes sense. For the one single instrument setting it does seem to work though, so an option could be to keep that? And throw an error otherwise saying that other specifications are not implemented?

At least when I've been presenting results it is the test of weak instruments that most people have been asking for. I don't think I would be capable of implementing it though...

**Comment by adamaltmejd** [comment]
I guess it would actually make more sense to implement the Montiel Olea-Pflueger (2013) (weakivtest in Stata) instead as @apoorvalal is suggesting. Then, users could just be referred to use that test instead of KPR. 

Did you ever start working on an implementation @apoorvalal? Would be happy to help out if there is anything I can do?

**Comment by apoorvalal** [comment]
I have a very minimal implementation of it in the package for our paper https://github.com/apoorvalal/ivDiag/blob/master/R/effF.R
Although I've come around to the position that we should probably just be reporting Anderson-Rubin intervals anyway, which is fairly standard in its implementation https://github.com/apoorvalal/ivDiag/blob/master/R/AR_test.R and shouldn't be too bad to incorporate into fixest
(I changed the original implementation from `ivpack` to work with `felm` objects [I started work on this before I started using `fixest`].

**Comment by lrberge** [comment]
@adamaltmejd: sure I can make it available only for the single case, that seems reasonable. 

Otherwise, I'm overhauling completely how `fitstats` are computed internally. After the changes, making contributions to fit statistics will be super super easy (I'll also write a contributing guide). So if you feel to contribute, it will be easy in a few weeks. Another feature that will be automatic is that when `lean = TRUE`, all fit stats available for the model will be directly integrated, making other functions work properly down the road.

**Comment by adamaltmejd** [comment]
That sounds like a great idea. Give me a shout out when its done and I might have time to take a look at implementing F^eff.

**Comment by JakubKomarek** [comment]
> ## K-P error
> 
> Computing the Kleibergen-Paap F-statistic using `fitstat(mod, "kpr")` produces the following error with the dev version of `fixest`. The equivalent computation in `lfe` works fine (and is identical to the documented `ivreg2` version in stata).
> 
> ```
> Error in str2lang(value_raw): <text>:2:0: unexpected end of input
> 1: (+Intercept
>    ^
> Traceback:
> 
> 1. fitstat(m_feols, "kpr")
> 2. kp_stat(x)
> 3. proj_on_U(x, Z)
> 4. resid(feols.fit(Z, U))
> 5. feols.fit(Z, U)
> 6. feols(env = env)
> 7. .xpd(rhs = fml[[3]])
> 8. value2stringCall(rhs, call = TRUE, check = check)
> 9. str2lang(value_raw)
> ```
> 
> MWE:
> 
> ```
> library(data.table); library(fixest); library(lfe)
> set.seed(42)
> N = 1e3
> df = data.table(
>   e = rnorm(N),
>   z1 = rbinom(N, 1, 0.3),
>   z2 = rnorm(N)
> )
> df[, x := 0.2 * z1 + 0.3 * z2 + e * 1.5][
>     ,y := x + e]
> 
> # %%
> m_felm = felm(y ~ 1 | 0 | (x ~ z1 + z2), df)
> # KP F stat in LFE object / identical in stata's ivreg2
> m_felm$stage1$rob.iv1fstat
> 
> # %%
> m_feols = feols(y ~ 1 | x ~ z1 + z2, df)
> fitstat(m_feols, "kpr")
> # error
> ```
> 
> ## Effective F statistic
> 
> Also I was wondering if there's any interest in including the effective F statistic (which is identical to K-P in just-identified single-instrument+single-treatment settings - see [2] for details ).
> 
> As part of a review paper I'm working on with coauthors, I'm implementing the Pflueger-Montiel Olea Effective F statistic [1], which is recommended by the review paper by Andrews, Stock, and Sun [2] manually for now using the simplified formula ![image](https://user-images.githubusercontent.com/12086926/121828291-ffcf1980-cc73-11eb-8ef3-e2291be01571.png)
> 
> from the Andrews et al paper (the original paper is written in archaic notation with y and Y as the outcome and treatment respectively; ew). Pretty straightforward to implement / I can send a pull request with the implementation if you think there's enough interest.
> 
> happy to move to related F-stat thread if preferred #117
> 
> [1] http://www.joseluismontielolea.com/Montiel-OleaJBES.pdf [2] https://scholar.harvard.edu/files/wirev_092218-_corrected_0.pdf

Hi, I would surely appreciate your implementation of Pflueger-Montiel Olea Effective F statistic!

**Comment by DavidMarguerit** [comment]
Hello,

Thank you for this fantastic package. I am getting the same error as @turbanisch.

The error seems to be caused by these lines in the `kp_stat` function:

```
    vcov = x$summary_flags$vcov
    ssc = x$summary_flags$ssc
    
    meat = vcov(x_new, vcov = vcov, ssc = ssc, sandwich = FALSE)
    vhat = solve(K, t(solve(K, meat)))
```

Any idea how to solve this issue?

**Comment by turbanisch** [comment]
Another year, this time I'm getting `Error in chol.default(crossprod(X_proj)) : 
  the leading minor of order 1 is not positive` similar to @adamaltmejd above. Could you perhaps give an update on what is the current state of the issue, @lrberge? I just mean whether you are going to attempt to fix this at some point or if we should rather go look somewhere else? 🙏
Is anyone aware of a solution that does not involve re-running the regressions in Stata?

**Comment by elskrstn** [comment]
Hello,

@lrberge thanks for the package and thank you very much for not having removed the K-P test! There are still some people out here trying to make use of it :D

I have adjusted the test for my case and just want to share some insights for anyone having similar issues. Please beware that I am relatively new to R and also to the fixest package. 

I have a feols-estimation for which I attempted the K-P test with the same number of endogenous variables (2) as instruments (2).

The current underlying function in usage is as follows:

"function (x) 
{
    if (!isTRUE(x$iv) || !x$iv_stage == 2) 
        return(NA)
    X_proj = as.matrix(resid(summary(x, stage = 1)))
    Z = model.matrix(x, type = "iv.inst")
    Z_proj = proj_on_U(x, Z)
    k = n_endo = ncol(X_proj)
    l = n_inst = ncol(Z)
    q = min(k, l) - 1
    if (n_endo == 1) {
        PI = t(coef(summary(x, stage = 1)))
    }
    else {
        PI = coef(summary(x, stage = 1))
    }
    PI = PI[, colnames(PI) %in% x$iv_inst_names_xpd, drop = FALSE]
    Fmat = chol(crossprod(Z_proj))
    Gmat = chol(crossprod(X_proj))
    theta = Fmat %*% t(solve(t(Gmat)) %*% PI)
    if (n_inst == n_endo) {
        svd_decomp = svd(theta)
        u = svd_decomp$u
        vt = t(svd_decomp$v)
    }
    else {
        svd_decomp = mat_svd(theta)
        u = svd_decomp$u
        vt = svd_decomp$vt
    }
    u_sub = u[k:l, k:l, drop = FALSE]
    vt_sub = vt[k, k]
    vt_k = vt[1:k, k, drop = FALSE]
    ssign = function(x) if (x == 0) 
        1
    else sign(x)
    if (k == l) {
        a_qq = ssign(u_sub[1]) * u[1:l, k:l, drop = FALSE]
        b_qq = ssign(vt_sub[1]) * t(vt_k)
    }
    else {
        a_qq = u[1:l, k:l] %*% (solve(u_sub) %*% mat_sqrt(u_sub %*% 
            t(u_sub)))
        b_qq = mat_sqrt(vt_sub %*% t(vt_sub)) %*% (solve(t(vt_sub)) %*% 
            t(vt_k))
    }
    kronv = kronecker(b_qq, t(a_qq))
    lambda = kronv %*% c(theta)
    VCOV_TYPE = attr(x$cov.scaled, "type")
    if (identical(VCOV_TYPE, "IID")) {
        vlab = chol(tcrossprod(kronv)/nrow(X_proj))
    }
    else {
        K = t(kronecker(Gmat, Fmat))
        my_scores = do.call(cbind, lapply(1:ncol(X_proj), function(i) Z_proj * 
            X_proj[, i]))
        x_new = x
        x_new$scores = my_scores
        vcov = x$summary_flags$vcov
        ssc = x$summary_flags$ssc
        meat = vcov(x_new, vcov = vcov, ssc = ssc, sandwich = FALSE)
        vhat = solve(K, t(solve(K, meat)))
        n = nobs(x) - identical(VCOV_TYPE, "cluster")
        df_resid = degrees_freedom(x, "resid", stage = 1)
        vhat = vhat * n/df_resid
        vlab = kronv %*% vhat %*% t(kronv)
    }
    r_kp = t(lambda) %*% solve(vlab, lambda)
    kp_df = n_inst - n_endo + 1
    kp_f = r_kp/n_inst
    kp_p = pchisq(kp_f, kp_df, lower.tail = FALSE)
    list(stat = kp_f, p = kp_p, df = kp_df)
}"


The first problem I encountered was the line:
"PI = PI[, colnames(PI) %in% x$iv_inst_names_xpd, drop = FALSE]".
PI then became a data.frame rather than a matrix and theta could not be evaluated (two lines after); so this is the same error as yours @turbanisch in 2022. Changing the line to
"PI = as.matrix((PI[, colnames(PI) %in% x$iv_inst_names_xpd, drop = FALSE]))" 
solved it.

The second problem I encountered was then as @DavidMarguerit in the specification of vcov and ssc. Since they rely on the specifications of a summary.fixest, it seems crucial to define a summarized model for the kp_stat function to work? (I at least did not know.) Further, it seems that se or vcov has to be specified in the summary.fixest, otherwise the line
 "meat = vcov(x_new, vcov = vcov, ssc = ssc, sandwich = FALSE)"
 will induce further trouble. Moreover, if one looks for clustered standard errors, one should define them via se and then also specify ssc (even if it may just be the default specifications) so that the meat can be computed. 
Some versions of vcov specifications remain buggy, e.g. specifying a variable through vcov (but since specifying through se works, it is not so detrimental I guess).

Hope this is of help and perhaps @lrberge although you seem to not be overly enthusiastic about this test :D maybe you find some time to fix the line and ensure PI as a matrix.

Cheers!

**Comment by karldw** [comment]
Hi @elskrstn, I'm another fixest and KP-stat user. I just submitted a PR (https://github.com/lrberge/fixest/pull/612) to address the `as.matrix` issue. There's a separate issue for the case with non-IID errors and unequal numbers of endogenous and IV variables. I added a warning for that case, but did not implement the calculation.
 

I wanted to ask about two other points you raised:

* You asked, "it seems crucial to define a summarized model for the kp_stat function to work?"

I think the existing code does this here, but if you've found issues where you're not getting the expected answer, it'd probably be good to file another issue! https://github.com/lrberge/fixest/blob/c18916605c7a46e51cfb49d0718389d80ab6cf1d/R/fitstats.R#L664-L666


* You also noted "Some versions of vcov specifications remain buggy, e.g. specifying a variable through vcov". Have you had issues with the formula syntax described in the `fitstat` help? If you're trying to specify a clustering variable, the `cluster` argument might be easier.

```
vcov: Versatile argument to specify the VCOV. In general, it is
      either a character scalar equal to a VCOV type, either a
      formula of the form: ‘vcov_type ~ variables’. The VCOV types
      implemented are: "iid", "hetero" (or "HC1"), "cluster",
      "twoway", "NW" (or "newey_west"), "DK" (or "driscoll_kraay"),
      and "conley". It also accepts object from ‘vcov_cluster’,
      ‘vcov_NW’, ‘NW’, ‘vcov_DK’, ‘DK’, ‘vcov_conley’ and ‘conley’.
      It also accepts covariance matrices computed externally.
      Finally it accepts functions to compute the covariances. See
      the ‘vcov’ documentation in the vignette.
```
