### ISSUE TITLE
lag argument in l function does not take a scalar.

### ISSUE THREAD

**Issue by seunghoon001** [lrberge/fixest#44]
Thank you for giving us such a fantastic package! 

I think I found a minor bug in l function: it does not take a number (rather than a vector) for its lag argument. 

```
library(fixest)
data("base_did")
pdat = panel(base_did, ~id+period)
```
The following does not work.
```
feols(y ~ l(x1, 2), pdat)
```
But this works. 
```
feols(y ~ l(x1, 2:2), pdat)
```

**Comment by lrberge** [comment]
Thanks a lot for the report! 

That's a bug indeed, but coming from a dependency: [dreamerr](https://cran.r-project.org/package=dreamerr). I've just fixed a sneaky bug occurring in rare occasions. 
I've submitted the new version of `dreamerr` to the CRAN, it should be there soon.

**Comment by lrberge** [comment]
Hi, is it fixed for you? Or you're still encountering a bug?

**Comment by seunghoon001** [comment]
I still have the bug and am using l(x1, 2:2). Thanks for checking in with me!

**Comment by seunghoon001** [comment]
Oh, sorry. I thought I updated dreamerr. I works after updating. Thank you so much for your response!
