### ISSUE TITLE
feols: R crashes with "Floating point exception" when 1 of the 2 fe is super high dim

### ISSUE THREAD

**Issue by zozotintin** [lrberge/fixest#56]
# Problem
My R crashes when I use `feols` with 2 fixed effects, one with 41 million dim and another with 61 dim. The following are the steps to create this behavior. I can send you the data if you want. It is a 2.4 GB parquet with 15 GB uncompressed.

# Environment Info
```r
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS/LAPACK: /home/poyu/anaconda3/lib/libopenblasp-r0.3.12.so

locale:
 [1] LC_CTYPE=en_HK.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_HK.UTF-8        LC_COLLATE=en_HK.UTF-8    
 [5] LC_MONETARY=en_HK.UTF-8    LC_MESSAGES=en_HK.UTF-8   
 [7] LC_PAPER=en_HK.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_HK.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] fixest_0.7.1      stringr_1.4.0     data.table_1.13.2 magrittr_1.5     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6        Formula_1.2-4       tidyselect_1.1.0   
 [4] bit_4.0.4           lattice_0.20-41     RClickhouse_0.5.2  
 [7] R6_2.5.0            rlang_0.4.8         dplyr_1.0.2        
[10] tools_4.0.3         grid_4.0.3          nlme_3.1-150       
[13] DBI_1.1.0           dbplyr_2.0.0        ellipsis_0.3.1     
[16] bit64_4.0.5         assertthat_0.2.1    tibble_3.0.4       
[19] lifecycle_0.2.0     numDeriv_2016.8-1.1 crayon_1.3.4       
[22] purrr_0.3.4         vctrs_0.3.4         glue_1.4.2         
[25] sandwich_3.0-0      stringi_1.5.3       compiler_4.0.3     
[28] dreamerr_1.2.1      pillar_1.4.6        generics_0.1.0     
[31] zoo_1.8-8           pkgconfig_2.0.3  
```

# Panel Summary
```r
> str(panel)
Classes ‘data.table’ and 'data.frame':  768417260 obs. of  5 variables:
 $ fe_a: int  0 0 0 0 0 0 0 0 0 0 ...
 $ fe_b: int  25 135 289 291 410 459 487 524 609 644 ...
 $ fe_t: int  24243 24243 24243 24243 24243 24243 24243 24243 24243 24243 ...
 $ dep : int  0 0 0 0 3 1 0 0 0 0 ...
 $ ind : int  5264 434 6607 3180 266 8363 2907 786 451 2986 ...
 - attr(*, "data.type")= chr [1:5] "Nullable(Int32)" "Nullable(Int32)" "Int32" "Int32" ...
 - attr(*, ".internal.selfref")=<externalptr> 
```
```r
> head(panel)
   fe_a fe_b  fe_t dep  ind
1:    0   25 24243   0 5264
2:    0  135 24243   0  434
3:    0  289 24243   0 6607
4:    0  291 24243   0 3180
5:    0  410 24243   3  266
6:    0  459 24243   1 8363
```
```r
> nrow(panel)
[1] 768417260
> object.size(panel)
15368347440 bytes
```
```r
> panel[, length(unique(fe_a))]
[1] 98813
> panel[, length(unique(fe_b))]
[1] 500
> panel[, length(unique(fe_t))]
[1] 61
```
```r
> panel[, summary(dep)]
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.0000  0.0000  0.5668  1.0000 12.0000 
> panel[, summary(ind)]
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
      0    1065    3401    8035    9330  439978   15133 
```

Specifically, `fe_a^fe_b` creates a fixed effect with 40,989,872 dim.

# Regression that Crashes
```r
> fml = dep ~ ind | fe_a^fe_b + fe_t
> model = feols(fml, panel)
NOTE: 15,133 observations removed because of NA values (LHS: 0, RHS: 15,133, Fixed-effects: 0).
Floating point exception (core dumped)
```
The same formulation works in `lfe::felm`, but it runs for 2,200 secs.

# Additional Specs that I Tested
Works when
- `fml = dep ~ ind | fe_a^fe_b`\
(Works with only 1 fe no matter how high dim)
- `fml = dep ~ ind | fe_a + fe_b + fe_c`\
(Works with 100K + 500 + 61)

Crashes when
- I pre-interact `fe_a` and `fe_b` with something like\
`panel[, fe_a_b := fe_a * 500 + fe_b]`\
and run `fml = dep ~ ind | fe_a_b + fe_t`
- `fml = dep ~ ind | fe_a + fe_b^fe_t`\
(Crashes with 100K + 30K)
- I use another non-Anaconda R without optimized BLAS with the version info below
```r
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_HK.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_HK.UTF-8        LC_COLLATE=en_HK.UTF-8    
 [5] LC_MONETARY=en_HK.UTF-8    LC_MESSAGES=en_HK.UTF-8   
 [7] LC_PAPER=en_HK.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_HK.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] fixest_0.7.1      stringr_1.4.0     data.table_1.13.2
[4] magrittr_1.5     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6        pillar_1.4.4        compiler_3.6.3     
 [4] dreamerr_1.2.1      dbplyr_1.4.4        tools_3.6.3        
 [7] bit_1.1-15.2        lifecycle_0.2.0     tibble_3.0.1       
[10] nlme_3.1-144        lattice_0.20-40     pkgconfig_2.0.3    
[13] texreg_1.37.5       rlang_0.4.6         DBI_1.1.0          
[16] rstudioapi_0.11     xfun_0.19           httr_1.4.2         
[19] dplyr_1.0.0         knitr_1.30          generics_0.0.2     
[22] vctrs_0.3.1         bit64_0.9-7         grid_3.6.3         
[25] tidyselect_1.1.0    glue_1.4.1          RClickhouse_0.5.2  
[28] R6_2.4.1            Formula_1.2-3       purrr_0.3.4        
[31] blob_1.2.1          ellipsis_0.3.1      assertthat_0.2.1   
[34] numDeriv_2016.8-1.1 sandwich_2.5-1      stringi_1.5.3      
[37] crayon_1.3.4        zoo_1.8-8
```

**Comment by lrberge** [comment]
Thanks you very much for the very clear report.

I did correct that kind of bugs in the previous version but then I completely rewrote the internal code and reintroduced some of them... I must have been tired!

So far, I see at least two undefined behaviors due to large data sets. But actually for your data set they should occur only if nb_FE >= 2 and kind of randomly, no matter the size of the FEs. 

I'll let you know when I push the fixes on GH. Hopefully they're the only bugs left.

**Comment by zozotintin** [comment]
Indeed for my dataset `feols` crashes only (when I use 2 or more fixed effects) and (when one of them is extremely large, or when both of them are moderately large). `feols` works perfectly with 1 fixed effect even when the dimension as large as 100 million. Thank you for your effort and I am looking forward to the fixes in the coming updates.

**Comment by lrberge** [comment]
Hi, I've just pushed the changes to GH.

The dev version should work. At least if you get an error, it should be different from the first one! :-)

The dev version really incorporates major changes in other places so I hope that I haven't introduced other problems (although the tests look OK).

Let me know!

**Comment by zozotintin** [comment]
It is now working properly. Thank you very much for your impressive work. It really saves my day as it cuts the runtime down to only 1/4 compared to `lfe::felm`.


BTW, some minor bugs still remain when the dependent or independent variables are `integer`
```r
> fml = dep ~ ind | fe_a^fe_b + fe_t
> system.time(model <- fixest::feols(fml, panel))
NOTE: 15,133 observations removed because of NA values (LHS: 0, RHS: 15,133, Fixed-effects: 0).
Error in cpp_demean(y, X, n_vars_X, weights, iterMax = fixef.iter, diffMax = fixef.tol,  : 
  REAL() can only be applied to a 'numeric', not a 'integer'
Timing stopped at: 141.6 79.47 190.7
```
Although I can get around it with
```r
> fml = as.numeric(dep) ~ as.numeric(ind) | fe_a^fe_b + fe_t
> system.time(model <- fixest::feols(fml, panel))
NOTE: 15,133 observations removed because of NA values (LHS: 0, RHS: 15,133, Fixed-effects: 0).
   user  system elapsed 
487.786 116.844 423.421 
```
so this is not really a big deal at this moment. But I guess it's still something that needs to be fixed in later updates.

**Comment by lrberge** [comment]
Fantastic! I'm glad it worked!

I'm a bit puzzled by the bug... because I can't replicate it. And it really shouldn't appear since the variables are converted way before getting to `cpp_demean`.
Could you check if the following code produces an error on your machine? (On mine it works fine.)
```R
base = iris
names(base) = c("y", "x1", "x2", "x3", "species")
base$y_int = as.integer(base$y) ; base$x1_int = as.integer(base$x1)

feols(y_int ~ x1_int, base)
```
If you don't get an error, I'll have to dig deeper to understand why it pops for your specific setup.

**Comment by zozotintin** [comment]
The `iris` example works fine when there is no fixed effects.
```r
> base = iris
> names(base) = c("y", "x1", "x2", "x3", "species")
> base$y_int = as.integer(base$y) ; base$x1_int = as.integer(base$x1)
> feols(y_int ~ x1_int, base)
OLS estimation, Dep. Var.: y_int
Observations: 150 
Standard-errors: Standard 
            Estimate Std. Error t value  Pr(>|t|)    
(Intercept)  5.91930   0.347799 17.0190 < 2.2e-16 ***
x1_int      -0.20123   0.128844 -1.5618  0.120467    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-likelihood: -185.27   Adj. R2: 0.00957 
```


But this error appears when I add any fixed effect.
```r
> feols(y_int ~ x1_int | species, base)
Error in cpp_demean(y, X, n_vars_X, weights, iterMax = fixef.iter, diffMax = fixef.tol,  : 
  REAL() can only be applied to a 'numeric', not a 'integer'
```

**Comment by lrberge** [comment]
OMG I forgot the FE... Very sorry! I think I shouldn't work past some hour...

Anyway, that's fixed, thanks for the report!

**Comment by zozotintin** [comment]
Thank you. I tested on both the small and big tables and ```feols``` works perfectly. Thank you very much for your impressive work!

**Comment by lrberge** [comment]
Thanks for checking. :-)

By the way, I've just added a set of stepwise estimation tools that are efficient for feols with multi FEs. If you have to use different sets of expl. vars I think it can save a lot of time with your data set.

Since the issue is solved, I'm closing. Thanks again!
