### ISSUE TITLE
summary with lean still produces a long vector obsRemoved

### ISSUE THREAD

**Issue by zozotintin** [lrberge/fixest#81]
When using `summary` with option `lean` set to true, the field `obsRemoved` is not cleaned. Sometimes `obsRemoved` can be very long and close to order O(N), and I will have to clean it myself with `model_summary$obsRemoved = NULL`. I am not sure whether this value is used in calculating other statistics, but if not then perhaps this attribute can be cleaned to save more space.

**Comment by lrberge** [comment]
Thanks, it was an oversight... there are just too many objects!!! I've also added `iv_residuals` that I had forgotten to include.

**Comment by zozotintin** [comment]
I just found that in the IV regression object, the `iv_first_stage` and `se_info` still carries O(N) objects. Not sure whether you fixed the problem or not. I was using commit `a1053d7f`.

**Comment by zozotintin** [comment]
FYI, this is the code I used to trim down the IV model in commit `a1053d7f`
```r
model_summary$iv_first_stage$fixef_id = NULL
model_summary$iv_first_stage$obsRemoved = NULL
model_summary$iv_first_stage$residuals = NULL
model_summary$iv_first_stage$sumFE = NULL
model_summary$iv_first_stage$fitted.values = NULL
model_summary$iv_first_stage$fitted.values_demean = NULL
model_summary$iv_first_stage$scores = NULL
model_summary$se_info$cluster = NULL
model_summary$summary_flags$call_env = NULL
```

**Comment by lrberge** [comment]
Thanks for the report, it should be fixed now.

**Comment by zozotintin** [comment]
I just found that in `0.8.3`, the `fitted.values_demean` in `iv_first_stage` is still not cleaned.

**Comment by lrberge** [comment]
Gosh, I will never get rid of it.... Thanks for the clear report, I've updated just now. We're getting closer :-)
